### ISSUE TITLE
Sorting of results according to lambda

### ISSUE THREAD

**Issue by voellerer** [aalfons/robustHD#27]
sparseLTS() as well as sparseS() sort the results when calling the function with a lambda-vector from results when using largest value of lambda to results when using smallest value of lambda. 

sparseMM(), however, doesn't do that. Can we fix that?

**Comment by aalfons** [comment]
<code>sparseS()</code> and <code>sparseMM()</code> will no longer be developed further.  Users can use package <code>pense</code> instead.
