### ISSUE TITLE
Robustness weights in sparseS()

### ISSUE THREAD

**Issue by aalfons** [aalfons/robustHD#29]
Current implementation of weights in FAST-S algorithm is only valid for <code>lambda</code> different from 0. 

For a fixed <code>lambda</code> grid, we need to check for special case <code>lambda = 0</code> and compute weights as for the unpenalized S-estimator in that case.

When <code>lambda</code> is selected on each weighted subset, we have to exclude <code>lambda = 0</code> in order to select <code>lambda</code> only from values where the weights are appropriate.

**Comment by voellerer** [comment]
Implementation should also be correct for lambda equal to zero. See derivations in email.

**Comment by aalfons** [comment]
<code>sparseS()</code> will no longer be developed further.  Users can use package <code>pense</code> instead.
