### ISSUE TITLE
Comparison of sparseS() in fullPath and redesign-code

### ISSUE THREAD

**Issue by voellerer** [aalfons/robustHD#30]
Problems in redesign:

1) number of iterations in M-scale changed inside the loop. Thus, after first sample, all fixed point iterations are done until convergence

2) After initial I-steps continueSteps needs to be set to TRUE. (Now it often happens that no further I-steps are carried out)

3) in sparseS, the objective function can also increase. Thus the difference between the previous and the current criterium of an I-step can be negative. Therefore, an absolute value needs to be applied.

**Comment by aalfons** [comment]
<code>sparseS()</code> will no longer be developed further.  Users can use package <code>pense</code> instead.
