### ISSUE TITLE
How `robustHD::winsorize` to handle missing value? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [aalfons/robustHD#36]
Hi Andreas, 

How `robustHD::winsorize` to handle missing value?  Should imputation be performed before `winsorize`

Thanks. 

Shicheng

**Comment by aalfons** [comment]
Hi Shicheng,

There is no missing value handling in <code>winsorize</code>, it assumes that the data are complete. So yes, you should perform imputation beforehand.

Best,
Andreas
